# name: Create envfile

# on: [push]

# jobs:
#   create-envfile:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Make envfile
#         uses: SpicyPizza/create-envfile@v1.2
#         with:
#           envkey_SOME_API_KEY: "123456abcdef"
#           directory: ./
#           file_name: .env
#           fail_on_empty: false

# on:
#   push:
#     branches:
#       - main
# jobs:
#   create_env_file_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Create .env file
#         uses: ozaytsev86/create-env-file@v1
#         with:
#           ENV_TEST_API_KEY: ${{ secrets.SERVER }}

name: Create envfile

on: [push]

jobs:
  create-envfile:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        run: |
          touch .env
          echo API_ENDPOINT="https://xxx.execute-api.us-west-2.amazonaws.com" >> .env
          echo API_KEY=${{ secrets.SERVER }} >> .env
          cat .env
